version: '3.8'

services:
  milvus:
    build: .
    container_name: milvus-standalone
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    volumes:
      - ./volumes/milvus:/var/lib/milvus
      - ./embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./user.yaml:/milvus/configs/user.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
